import { describe, expect, test } from 'bun:test'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')

async function readRepoFile(path: string) {
  return readFile(join(root, path), 'utf8')
}

describe('predeploy check wiring', () => {
  test('keeps predeploy diagnostics Thai-first', async () => {
    const predeploy = await readRepoFile('scripts/predeploy-check.ts')

    expect(predeploy).toContain('ไฟล์ deploy ที่จำเป็นต้องมีครบ')
    expect(predeploy).toContain('หัวข้อ Markdown สำคัญต้องเป็น Thai-first')
    expect(predeploy).toContain('คำสั่งในเอกสารและ workflow ต้องตรงกับ package scripts')
    expect(predeploy).toContain('collectDocsCommandAuditResult')
    expect(predeploy).toContain('collectDefaultAuditedCommandFiles')
    expect(predeploy).toContain('collectMarkdownHeadingFiles')
    expect(predeploy).toContain('collectDecisionMarkdownFiles')
    expect(predeploy).toContain('memory/decisions')
    expect(predeploy).toContain('startsWith')
    expect(predeploy).toContain('memory/decisions/')
    expect(predeploy).toContain('includes decision files in the default command audit set')
    expect(predeploy).toContain('ไฟล์ทดสอบต้องถูกผูกเข้า QA gate')
    expect(predeploy).toContain('collectTestCoverageAuditResult')
    expect(predeploy).toContain('scripts/test-coverage-audit.ts')
    expect(predeploy).toContain('scripts/test-coverage-audit.test.ts')
    expect(predeploy).toContain('collectRepoOwnedTestFiles')
    expect(predeploy).toContain('flags stale bun test file references')
    expect(predeploy).toContain('formatPredeployCheckError(error)')
    expect(predeploy).toContain('formatUnknownDiagnosticText(error, 500)')
    expect(predeploy).toContain('formatUnknownDiagnosticText')
    expect(predeploy).toContain('formats unknown smoke diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped API smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped deploy status errors without stringifying raw objects')
    expect(predeploy).toContain('returns structured JSON when root identity cannot be read')
    expect(predeploy).toContain('returns structured JSON when health cannot be read after root identity passes')
    expect(predeploy).toContain('rootIdentity.ok=false')
    expect(predeploy).toContain('memory/production/checklist.md')
    expect(predeploy).toContain('decision `0023` dangerous link protocol contract')
    expect(predeploy).toContain('memory audit ครอบ 33 Markdown files')
    expect(predeploy).toContain('docs command audit ครอบ 335 refs')
    expect(predeploy).toContain('frontend static audit allowlist guard')
    expect(predeploy).toContain('aria-disabled reason guard')
    expect(predeploy).toContain('placeholder-link guard')
    expect(predeploy).toContain('no-op handler guard')
    expect(predeploy).toContain('dangerous link protocol guard')
    expect(predeploy).toContain('interactive `aria-disabled` controls/links')
    expect(predeploy).toContain('frontend dangerous protocol decision pass')
    expect(predeploy).toContain('formats object-shaped smoke doctor errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped local smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped readiness errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped image smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped live chat smoke errors without stringifying raw objects')
    expect(predeploy).toContain('validates live stream chat smoke events')
    expect(predeploy).toContain('validateLiveChatSmokeStream')
    expect(predeploy).toContain('requires distinct wallet debits for normal and stream chat')
    expect(predeploy).toContain('findMatchingChatDebits')
    expect(predeploy).toContain('streamWalletTransactionId')
    expect(predeploy).toContain('validateLiveChatSmokeStream(events)')
    expect(predeploy).toContain('walletDebits=')
    expect(predeploy).toContain('chatId: liveChatId')
    expect(predeploy).toContain('requiredApiSmokeHandoffEvidenceFields')
    expect(predeploy).toContain('positiveNumberApiSmokeHandoffEvidenceFields')
    expect(predeploy).toContain('hasCompleteApiSmokeHandoffEvidence')
    expect(predeploy).toContain('options.handoffEvidence && hasCompleteApiSmokeHandoffEvidence(options.handoffEvidence)')
    expect(predeploy).toContain("'Chat smoke normal tokens': 0")
    expect(predeploy).toContain('หมายเหตุ combined summary')
    expect(predeploy).toContain('token/elapsedMs มากกว่า 0')
    expect(predeploy).toContain('Chat smoke stream tokens')
    expect(predeploy).toContain('summary ยังไม่มี `handoffEvidence`')
    expect(predeploy).toContain('positive token/elapsed values')
    expect(predeploy).toContain('combined `api:smoke:live` JSON summary must omit `handoffEvidence`')
    expect(predeploy).toContain('live-provider routes (`POST /chat`, `POST /chat/stream`, `POST /creator/ai-draft`) require `live-smoke`')
    expect(predeploy).toContain('href = "#"')
    expect(predeploy).toContain('href={"#"}')
    expect(predeploy).toContain('href={\\\\`#\\\\`}')
    expect(predeploy).toContain("to = {'#'}")
    expect(predeploy).toContain('to={\\\\`#\\\\`}')
    expect(predeploy).toContain('Async no-op')
    expect(predeploy).toContain('Undefined no-op')
    expect(predeploy).toContain('Spaced no-op')
    expect(predeploy).toContain('Spaced async no-op')
    expect(predeploy).toContain('Spaced undefined no-op')
    expect(predeploy).toContain('throw new Error (\\\\`not implemented\\\\`)')
    expect(predeploy).toContain('Bad protocol')
    expect(predeploy).toContain('Bad spaced protocol')
    expect(predeploy).toContain('data:text/html,<h1>x</h1>')
    expect(predeploy).toContain('srcDoc={html}')
    expect(predeploy).toContain('srcdoc="<script>alert(1)</script>"')
    expect(predeploy).toContain('\\\\bsrcDoc\\\\s*=|\\\\bsrcdoc\\\\s*=')
    expect(predeploy).toContain('href\\\\s*=\\\\s*')
    expect(predeploy).toContain('to\\\\s*=\\\\s*')
    expect(predeploy).toContain('onClick\\\\s*=\\\\s*')
    expect(predeploy).toContain('throw\\\\s+new\\\\s+Error\\\\s*\\\\(')
    expect(predeploy).toContain(`console.error(
          'โหลดข้อมูลไม่สำเร็จ:',`)
    expect(predeploy).toContain('console\\\\.(?:error|warn)\\\\s*\\\\(')
    expect(predeploy).toContain('[\\\\s\\\\S]*?,\\\\s*error\\\\b[\\\\s\\\\S]*?\\\\)')
    expect(predeploy).toContain('javascript:')
    expect(predeploy).toContain('vbscript:')
    expect(predeploy).toContain('ห้ามใช้ลิงก์ protocol ที่รันโค้ดหรือ HTML ตรงใน frontend source')
    expect(predeploy).toContain('formats object-shaped env doctor errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped Supabase storage setup errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped e2e smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped knowledge diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped required DB check diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped DB-test skip diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped database health diagnostics without stringifying raw objects')
    expect(predeploy).toContain('redactUnknownDiagnosticText')
    expect(predeploy).toContain('object-shaped error')
    expect(predeploy).toContain('safeErrorTextForClassification')
    expect(predeploy).toContain('frontendErrorSecretPatterns')
    expect(predeploy).toContain('Lore/persona injection')
    expect(predeploy).toContain('New-tab links')
    expect(predeploy).toContain('reports raw auth error classifier regressions')
    expect(predeploy).toContain('error\\\\s*\\\\.\\\\s*message\\\\s*\\\\.\\\\s*toLowerCase')
    expect(predeploy).toContain('String\\\\s*\\\\(\\\\s*error\\\\s*\\\\)\\\\s*\\\\.\\\\s*toLowerCase')
    expect(predeploy).toContain('\\\\.test\\\\(\\\\s*error\\\\s*\\\\.\\\\s*message')
    expect(predeploy).toContain('error\\\\s*\\\\.\\\\s*message\\\\s*\\\\.\\\\s*match')
    expect(predeploy).toContain('setNote\\\\s*\\\\(\\\\s*error\\\\s+instanceof\\\\s+Error\\\\s*\\\\?\\\\s*error\\\\s*\\\\.\\\\s*message')
    expect(predeploy).toContain('state\\\\s*\\\\.\\\\s*error\\\\s*=\\\\s*action\\\\s*\\\\.\\\\s*error\\\\s*\\\\.\\\\s*message')
    expect(predeploy).toContain('providerClassificationMessage')
    expect(predeploy).toContain('rawRouteErrorLogPattern')
    expect(predeploy).toContain('rawAuthErrorResponseBypassPattern')
    expect(predeploy).toContain('ห้ามประกอบ AuthError response จาก error.code/error.message ตรงๆ')
    expect(predeploy).toContain('catches AuthError responses that bypass the public response helper')
    expect(predeploy).toContain('return authErrorResponse(error)')
    expect(predeploy).toContain('console\\\\.(?:error|warn)\\\\s*\\\\(\\\\s*error\\\\b\\\\s*(?:,|\\\\))')
    expect(predeploy).toContain('providerFailure[\\\\s\\\\S]*?,\\\\s*error\\\\b')
    expect(predeploy).toContain('catches raw provider error logging after classification')
    expect(predeploy).toContain('catches route raw error logging')
    expect(predeploy).toContain('redacts secret-shaped provider details before classification output')
    expect(predeploy).toContain('creatorDraftRetryRawMessage')
    expect(predeploy).toContain('creatorDraftRetryMessage')
    expect(predeploy).toContain('classifies object-shaped provider failures without stringifying raw objects')
    expect(predeploy).toContain('retries object-shaped text model errors without stringifying raw objects')
    expect(predeploy).toContain('redacts text-model retry classifier input before matching transient hints')
    expect(predeploy).toContain('assertThaiFirstMarkdownHeadings')
    expect(predeploy).toContain('0020-discover-decision-markdown-heading-files.md')
    expect(predeploy).toContain('`qa:repo` ล่าสุดผ่านวันที่ 2026-05-26')
    expect(predeploy).toContain('memory audit ครอบ 33 Markdown files')
    expect(predeploy).toContain('Decision/predeploy handoff lock ล่าสุดอยู่ถึง')
    expect(predeploy).toContain('0023-guard-dangerous-frontend-link-protocols.md')
    expect(predeploy).toContain('predeploy:check` audits decision Markdown dynamically')
    expect(predeploy).toContain('decision markdown files ถูก audit แบบ dynamic')
    expect(predeploy).toContain('stream live-provider handoff wording pass')
    expect(predeploy).toContain('missingDecisionIndexEntries')
    expect(predeploy).toContain('apps/backend/src/world-state.service.ts')
    expect(predeploy).toContain('frontend API helper contract')
    expect(predeploy).toContain('apps/frontend/src/lib/api.ts')
    expect(predeploy).toContain('ARG VITE_SUPABASE_ANON_PUBLIC=')
    expect(predeploy).toContain('VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_PUBLIC bun run build')
    expect(predeploy).toContain('สถานะโลกปัจจุบัน')
    expect(predeploy).toContain('Treat this as the current world state')
    expect(predeploy).toContain('uses a Thai-first prompt for live roleplay quality smoke')
    expect(predeploy).toContain('liveChatSmokePrompt')
    expect(predeploy).toContain('Reply as an atmospheric roleplay scene')
    expect(predeploy).toContain('apps/backend/prisma/qa-seed.ts')
    expect(predeploy).toContain('พูดกระชับแต่เป็นฉากครบ')
    expect(predeploy).toContain('ตอบสั้นแต่มีชั้นเชิง')
    expect(predeploy).toContain('^#\\s+\\d{4}\\s+-\\s+')
    expect(predeploy).toContain('ยังไม่มีข้อความที่ต้องมี')
    expect(predeploy).toContain("result.ok ? 'ผ่าน' : 'ไม่ผ่าน'")
    expect(predeploy).not.toContain("result.ok ? 'ok' : 'fail'")
    expect(predeploy).not.toContain('error: error instanceof Error ? error.message : String(error)')
    expect(predeploy).not.toContain('is missing ${missing.join')
    expect(predeploy).not.toContain('contains stale text')
  })

  test('locks Thai-first e2e labels for admin eval smoke', async () => {
    const predeploy = await readRepoFile('scripts/predeploy-check.ts')
    const e2eSmoke = await readRepoFile('tests/e2e/maprang-smoke.spec.ts')

    expect(e2eSmoke).toContain('ทดสอบคุณภาพพรอมป์และบริบท')
    expect(e2eSmoke).not.toContain('ทดสอบคุณภาพ prompt/context')
    expect(predeploy).toContain('ทดสอบคุณภาพพรอมป์และบริบท')
    expect(predeploy).toContain('prompt/context')
  })

  test('keeps the predeploy regression test in local and deployed QA gates', async () => {
    const packageJson = JSON.parse(await readRepoFile('package.json')) as { scripts?: Record<string, string> }
    const ciWorkflow = await readRepoFile('.github/workflows/ci.yml')
    const productionSmoke = await readRepoFile('.github/workflows/production-smoke.yml')
    const readme = await readRepoFile('README.md')
    const deploymentQa = await readRepoFile('DEPLOYMENT_QA.md')

    const qaRepo = packageJson.scripts?.['qa:repo'] ?? ''
    const qaLocal = packageJson.scripts?.['qa:local'] ?? ''
    const qaLocalOnlyCommands = qaLocal
      .split(/\s*&&\s*/)
      .map((command) => command.trim())
      .filter(Boolean)
    const qaLocalCommands = [qaRepo, qaLocal].flatMap((script) =>
      script
        .split(/\s*&&\s*/)
        .map((command) => command.trim())
        .filter(Boolean),
    )

    expect(packageJson.scripts?.['predeploy:check:test']).toBe('bun test scripts/predeploy-check.test.ts')
    expect(qaLocalOnlyCommands).toContain('bun run qa:repo')
    expect(qaLocalOnlyCommands).toContain('bun run smoke:doctor')
    expect(qaLocalOnlyCommands).toContain('bun run smoke:local')
    expect(qaLocalOnlyCommands).toContain('bun run api:smoke')
    expect(qaLocalCommands).toContain('bun run predeploy:check:test')
    expect(qaLocalCommands).toContain('bun run docs:commands')
    expect(qaLocalCommands).toContain('bun run docs:commands:test')
    expect(qaLocalCommands).toContain('bun run tests:audit')
    expect(qaLocalCommands).toContain('bun run tests:audit:test')
    expect(qaLocalCommands).toContain('bun run deploy:doctor:self-test')
    expect(qaLocalCommands).toContain('bun run security:audit')
    expect(qaLocalCommands).toContain('bun run security:audit:test')
    expect(qaLocalCommands).toContain('bun run import-cycle:audit')
    expect(qaLocalCommands).toContain('bun run import-cycle:audit:test')
    expect(qaLocalCommands).toContain('bun run api:audit')
    expect(qaLocalCommands).toContain('bun run api:audit:test')
    expect(qaLocalCommands).toContain('bun run frontend:env:test')
    expect(qaLocalCommands).toContain('bun run frontend:storage:test')
    expect(qaLocalCommands).toContain('bun run frontend:clipboard:test')
    expect(qaLocalCommands).toContain('bun run frontend:static:audit')
    expect(qaLocalCommands).toContain('bun run frontend:static:audit:test')
    expect(qaLocalCommands).toContain('bun run frontend:route:audit')
    expect(qaLocalCommands).toContain('bun run frontend:route:audit:test')
    expect(qaLocalCommands).toContain('bun run route-menu:audit')
    expect(qaLocalCommands).toContain('bun run route-menu:audit:test')
    expect(ciWorkflow.match(/name: ติดตั้ง dependencies ระดับ repo[\s\S]*?run: bun install --frozen-lockfile/g)?.length ?? 0).toBeGreaterThanOrEqual(2)
    expect(ciWorkflow).toContain('รัน local smoke จาก seed')
    expect(ciWorkflow).not.toContain('Install root dependencies')
    expect(ciWorkflow).toContain('bun run predeploy:check:test')
    expect(ciWorkflow).toContain('bun run docs:commands')
    expect(ciWorkflow).toContain('bun run docs:commands:test')
    expect(ciWorkflow).toContain('bun run tests:audit')
    expect(ciWorkflow).toContain('bun run tests:audit:test')
    expect(ciWorkflow).toContain('bun run deploy:doctor:self-test')
    expect(ciWorkflow).toContain('bun run frontend:env:test')
    expect(ciWorkflow).toContain('bun run frontend:storage:test')
    expect(ciWorkflow).toContain('bun run frontend:clipboard:test')
    expect(ciWorkflow).toContain('bun run frontend:static:audit')
    expect(ciWorkflow).toContain('bun run frontend:route:audit')
    expect(ciWorkflow).toContain('--build-arg VITE_SUPABASE_ANON_PUBLIC=ci-anon-public-key')
    expect(productionSmoke).toContain('bun run predeploy:check:test')
    expect(productionSmoke).toContain('bun run docs:commands')
    expect(productionSmoke).toContain('bun run docs:commands:test')
    expect(productionSmoke).toContain('bun run tests:audit')
    expect(productionSmoke).toContain('bun run tests:audit:test')
    expect(productionSmoke).toContain('bun run frontend:env:test')
    expect(productionSmoke).toContain('bun run frontend:storage:test')
    expect(productionSmoke).toContain('bun run frontend:clipboard:test')
    expect(productionSmoke).toContain('bun run frontend:static:audit')
    expect(productionSmoke).toContain('bun run frontend:route:audit')
    for (const docs of [readme, deploymentQa]) {
      expect(docs).toContain('bun run frontend:env:test')
      expect(docs).toContain('bun run frontend:storage:test')
      expect(docs).toContain('bun run frontend:clipboard:test')
    }
    for (const command of [
      'bun run security:audit',
      'bun run import-cycle:audit',
      'bun run api:audit',
      'bun run frontend:env:test',
      'bun run frontend:storage:test',
      'bun run frontend:clipboard:test',
      'bun run frontend:static:audit',
      'bun run frontend:route:audit',
      'bun run route-menu:audit',
    ]) {
      expect(ciWorkflow).toMatch(new RegExp(`-\\s+run:\\s+${command.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\r?\\n`))
      expect(productionSmoke).toMatch(new RegExp(`-\\s+run:\\s+${command.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\r?\\n`))
    }
    expect(productionSmoke).toContain('Backend URL ที่ต้องการทดสอบ')
    expect(productionSmoke).toContain('ตรวจ config ก่อนรัน smoke')
    expect(productionSmoke).toContain('รันทดสอบแชทจริงกับ AI คำสั่งนี้ใช้เครดิตผู้ให้บริการจริง')
    expect(productionSmoke).toContain('รันทดสอบสร้างรูปจริง คำสั่งนี้ใช้เครดิตสร้างรูปจริง')
    expect(productionSmoke).toContain('ยอดโทเคนขั้นต่ำของผู้ใช้ smoke ก่อนรันทดสอบแชทจริง')
    expect(productionSmoke).toContain('ตั้ง workflow input api_base_url หรือ repository secret SMOKE_API_BASE_URL ก่อนรัน smoke')
    expect(productionSmoke).not.toContain('Backend URL to test')
    expect(productionSmoke).not.toContain('รัน live AI chat smoke')
    expect(productionSmoke).not.toContain('รัน live image generation smoke')
    expect(productionSmoke).not.toContain('ยอดโทเคนขั้นต่ำของ smoke user ก่อนรัน live chat smoke')
    expect(productionSmoke).not.toContain('Validate smoke configuration')
    expect(productionSmoke).not.toContain('Minimum smoke-user token balance')
    expect(productionSmoke).not.toContain('Set workflow input api_base_url')
  })
})
