import { describe, expect, test } from 'bun:test'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')

async function readRepoFile(path: string) {
  return readFile(join(root, path), 'utf8')
}

describe('predeploy check wiring', () => {
  test('keeps predeploy diagnostics Thai-first', async () => {
    const predeploy = await readRepoFile('scripts/predeploy-check.ts')

    expect(predeploy).toContain('ไฟล์ deploy ที่จำเป็นต้องมีครบ')
    expect(predeploy).toContain('หัวข้อ Markdown สำคัญต้องเป็น Thai-first')
    expect(predeploy).toContain('คำสั่งในเอกสารและ workflow ต้องตรงกับ package scripts')
    expect(predeploy).toContain('collectDocsCommandAuditResult')
    expect(predeploy).toContain('collectDefaultAuditedCommandFiles')
    expect(predeploy).toContain('collectMarkdownHeadingFiles')
    expect(predeploy).toContain('collectDecisionMarkdownFiles')
    expect(predeploy).toContain('memory/decisions')
    expect(predeploy).toContain('startsWith')
    expect(predeploy).toContain('memory/decisions/')
    expect(predeploy).toContain('includes decision files in the default command audit set')
    expect(predeploy).toContain('ไฟล์ทดสอบต้องถูกผูกเข้า QA gate')
    expect(predeploy).toContain('collectTestCoverageAuditResult')
    expect(predeploy).toContain('scripts/test-coverage-audit.ts')
    expect(predeploy).toContain('scripts/test-coverage-audit.test.ts')
    expect(predeploy).toContain('collectRepoOwnedTestFiles')
    expect(predeploy).toContain('flags stale bun test file references')
    expect(predeploy).toContain('formatPredeployCheckError(error)')
    expect(predeploy).toContain('formatUnknownDiagnosticText(error, 500)')
    expect(predeploy).toContain('formatUnknownDiagnosticText')
    expect(predeploy).toContain('formats unknown smoke diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped API smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped deploy status errors without stringifying raw objects')
    expect(predeploy).toContain('returns structured JSON when root identity cannot be read')
    expect(predeploy).toContain('returns structured JSON when health cannot be read after root identity passes')
    expect(predeploy).toContain('rootIdentity.ok=false')
    expect(predeploy).toContain('memory/production/checklist.md')
    expect(predeploy).toContain('decision `0023` dangerous link protocol contract')
    expect(predeploy).toContain('decision `0024` share URL origin contract')
    expect(predeploy).toContain('decision `0025` cross-window messaging helper contract')
    expect(predeploy).toContain('decision `0026` frontend UI/route guard contract')
    expect(predeploy).toContain('memory audit ครอบ 36 Markdown files')
    expect(predeploy).toContain('docs command audit ครอบ 349 refs')
    expect(predeploy).toContain('raw UI error throw guard')
    expect(predeploy).toContain('cross-window messaging helper/guard')
    expect(predeploy).toContain('backend raw route return guard')
    expect(predeploy).toContain('frontend static audit allowlist guard')
    expect(predeploy).toContain('aria-disabled reason guard')
    expect(predeploy).toContain('placeholder-link guard')
    expect(predeploy).toContain('no-op handler guard')
    expect(predeploy).toContain('no-op submit guard')
    expect(predeploy).toContain('native dialog guard')
    expect(predeploy).toContain('event listener cleanup guard')
    expect(predeploy).toContain('share URL origin guard')
    expect(predeploy).toContain('dangerous link protocol guard')
    expect(predeploy).toContain('interactive `aria-disabled` controls/links')
    expect(predeploy).toContain('frontend dangerous protocol decision pass')
    expect(predeploy).toContain('frontend share URL origin decision pass')
    expect(predeploy).toContain('frontend cross-window messaging helper pass')
    expect(predeploy).toContain('frontend cross-window messaging decision pass')
    expect(predeploy).toContain('frontend UI/route guard decision pass')
    expect(predeploy).toContain('formats object-shaped smoke doctor errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped local smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped readiness errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped image smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped live chat smoke errors without stringifying raw objects')
    expect(predeploy).toContain('validates live stream chat smoke events')
    expect(predeploy).toContain('validateLiveChatSmokeStream')
    expect(predeploy).toContain('requires distinct wallet debits for normal and stream chat')
    expect(predeploy).toContain('findMatchingChatDebits')
    expect(predeploy).toContain('streamWalletTransactionId')
    expect(predeploy).toContain('validateLiveChatSmokeStream(events)')
    expect(predeploy).toContain('walletDebits=')
    expect(predeploy).toContain('chatId: liveChatId')
    expect(predeploy).toContain('requiredApiSmokeHandoffEvidenceFields')
    expect(predeploy).toContain('positiveNumberApiSmokeHandoffEvidenceFields')
    expect(predeploy).toContain('hasCompleteApiSmokeHandoffEvidence')
    expect(predeploy).toContain('options.handoffEvidence && hasCompleteApiSmokeHandoffEvidence(options.handoffEvidence)')
    expect(predeploy).toContain("'Chat smoke normal tokens': 0")
    expect(predeploy).toContain('หมายเหตุ combined summary')
    expect(predeploy).toContain('token/elapsedMs มากกว่า 0')
    expect(predeploy).toContain('Chat smoke stream tokens')
    expect(predeploy).toContain('summary ยังไม่มี `handoffEvidence`')
    expect(predeploy).toContain('positive token/elapsed values')
    expect(predeploy).toContain('combined `api:smoke:live` JSON summary must omit `handoffEvidence`')
    expect(predeploy).toContain('live-provider routes (`POST /chat`, `POST /chat/stream`, `POST /creator/ai-draft`) require `live-smoke`')
    expect(predeploy).toContain('href = "#"')
    expect(predeploy).toContain('href={"#"}')
    expect(predeploy).toContain('href={\\\\`#\\\\`}')
    expect(predeploy).toContain("to = {'#'}")
    expect(predeploy).toContain('to={\\\\`#\\\\`}')
    expect(predeploy).toContain('Async no-op')
    expect(predeploy).toContain('Undefined no-op')
    expect(predeploy).toContain('Spaced no-op')
    expect(predeploy).toContain('Spaced async no-op')
    expect(predeploy).toContain('Spaced undefined no-op')
    expect(predeploy).toContain('throw new Error (\\\\`not implemented\\\\`)')
    expect(predeploy).toContain('Bad protocol')
    expect(predeploy).toContain('Bad spaced protocol')
    expect(predeploy).toContain('data:text/html,<h1>x</h1>')
    expect(predeploy).toContain("open(url, '_blank')")
    expect(predeploy).toContain("alert('ใช้ toast แทน')")
    expect(predeploy).toContain("confirm('ใช้ modal แทน')")
    expect(predeploy).toContain("prompt('ใช้ form แทน')")
    expect(predeploy).toContain("window.postMessage(payload, '*')")
    expect(predeploy).toContain("window.postMessage(payload, 'https://app.example.com')")
    expect(predeploy).toContain("globalThis.addEventListener('message', handler)")
    expect(predeploy).toContain('reports browser event listeners without cleanup')
    expect(predeploy).toContain("window . addEventListener('scroll', closeOnScroll)")
    expect(predeploy).toContain('browserEventListenerRemovalPattern')
    expect(predeploy).toContain('frontend source ที่เพิ่ม browser event listener ต้องมี removeEventListener คู่กัน')
    expect(predeploy).toContain('builds character share URLs through the shared helper')
    expect(predeploy).toContain('reports direct location origin usage outside share URL helper')
    expect(predeploy).toContain('const bare = location . origin')
    expect(predeploy).toContain('directLocationOriginPattern')
    expect(predeploy).toContain('allowedFrontendLocationOriginFiles')
    expect(predeploy).toContain('shareUrl helper')
    expect(predeploy).toContain('routes cross-window messages through trusted origin helpers')
    expect(predeploy).toContain('allows message event listeners only inside cross-window messaging helper')
    expect(predeploy).toContain('allowedFrontendMessageOriginFiles')
    expect(predeploy).toContain('apps/frontend/src/lib/crossWindowMessaging.ts')
    expect(predeploy).toContain('srcDoc={html}')
    expect(predeploy).toContain('srcdoc="<script>alert(1)</script>"')
    expect(predeploy).toContain('\\\\bsrcDoc\\\\s*=|\\\\bsrcdoc\\\\s*=')
    expect(predeploy).toContain('href\\\\s*=\\\\s*')
    expect(predeploy).toContain('to\\\\s*=\\\\s*')
    expect(predeploy).toContain('onClick\\\\s*=\\\\s*')
    expect(predeploy).toContain('(?<![\\\\w.])(?:(?:window|globalThis)\\\\s*\\\\.\\\\s*)?open\\\\s*\\\\(')
    expect(predeploy).toContain('throw\\\\s+new\\\\s+Error\\\\s*\\\\(')
    expect(predeploy).toContain('console.error(')
    expect(predeploy).toContain("'โหลดข้อมูลไม่สำเร็จ:',")
    expect(predeploy).toContain('consoleErrorWarnAccessor')
    expect(predeploy).toContain('retrievedConsoleObjectValue')
    expect(predeploy).toContain('consoleNamespaceObjectAccessor')
    expect(predeploy).toContain('consoleObjectValue')
    expect(predeploy).toContain('consoleObjectMemberAccessor')
    expect(predeploy).toContain('consoleErrorWarnCallPrefix')
    expect(predeploy).toContain('consoleObjectAliasValue')
    expect(predeploy).toContain('consoleObjectAliasPattern')
    expect(predeploy).toContain('consoleErrorWarnAliasValue')
    expect(predeploy).toContain('consoleErrorWarnAliasPattern')
    expect(predeploy).toContain('reflectConsoleErrorWarnApplyPrefix')
    expect(predeploy).toContain('reflectObjectAccessor')
    expect(predeploy).toContain('reflectApplyAccessor')
    expect(predeploy).toContain('reflectApplyCallPrefix')
    expect(predeploy).toContain('reflectGetAccessor')
    expect(predeploy).toContain('reflectGetCallPrefix')
    expect(predeploy).toContain('reflectGetMethodCallPrefix')
    expect(predeploy).toContain('reflectGetMethodApplyPrefix')
    expect(predeploy).toContain('reflectGetMethodBindPrefix')
    expect(predeploy).toContain('objectDescriptorAccessor')
    expect(predeploy).toContain('objectDescriptorCallPrefix')
    expect(predeploy).toContain('objectDescriptorMethodCallPrefix')
    expect(predeploy).toContain('objectDescriptorMethodApplyPrefix')
    expect(predeploy).toContain('objectDescriptorMethodBindPrefix')
    expect(predeploy).toContain('retrievalMethodAliasValue')
    expect(predeploy).toContain('retrievalMethodAliasPattern')
    expect(predeploy).toContain('reflectObjectAliasValue')
    expect(predeploy).toContain('reflectObjectAliasPattern')
    expect(predeploy).toContain('objectObjectAliasValue')
    expect(predeploy).toContain('objectObjectAliasPattern')
    expect(predeploy).toContain('reflectApplyAliasValue')
    expect(predeploy).toContain('reflectApplyAliasPattern')
    expect(predeploy).toContain('promiseNamespaceRoot')
    expect(predeploy).toContain('promiseNamespaceObjectAccessor')
    expect(predeploy).toContain('retrievedPromiseObjectValue')
    expect(predeploy).toContain('promiseObjectValue')
    expect(predeploy).toContain('promiseObjectMemberAccessor')
    expect(predeploy).toContain('promiseObjectAliasValue')
    expect(predeploy).toContain('promiseObjectAliasPattern')
    expect(predeploy).toContain(String.raw`(?:window|globalThis)\\s*(?:\\?\\.|\\.)\\s*`)
    expect(predeploy).toContain(String.raw`["\']console["\']\\s*\\]`)
    expect(predeploy).toContain('${consoleObjectMemberAccessor}\\\\s*(?:(?:\\\\?\\\\.|\\\\.)\\\\s*(?:error|warn)|(?:\\\\?\\\\.)?\\\\s*\\\\[')
    expect(predeploy).toContain(String.raw`["\'](?:error|warn)["\']\\s*\\]`)
    expect(predeploy).toContain(String.raw`(?:\\?\\.|\\.)\\s*(?:call|apply)`)
    expect(predeploy).toContain(String.raw`(?:\\?\\.|\\.)\\s*bind`)
    expect(predeploy).toContain(String.raw`(?:\\?\\.)?\\s*\\[\\s*["\']apply["\']\\s*\\]`)
    expect(predeploy).toContain('rawFrontendErrorLogPatternFor')
    expect(predeploy).toContain('rawFrontendErrorArrayElementPatternFor')
    expect(predeploy).toContain('${rawExpression}')
    expect(predeploy).toContain('console.error(error)')
    expect(predeploy).toContain("console.warn(error, 'โหลดข้อมูลช้า')")
    expect(predeploy).toContain('console.error.call(console, error)')
    expect(predeploy).toContain("console.warn.apply(console, [error, 'โหลดข้อมูลช้า'])")
    expect(predeploy).toContain('console.error.bind(console)(error)')
    expect(predeploy).toContain("console.warn.bind(console)('โหลดข้อมูลช้า', error)")
    expect(predeploy).toContain('Reflect.apply(console.error, console, [error])')
    expect(predeploy).toContain("Reflect.apply(console.warn, console, ['โหลดข้อมูลช้า', error])")
    expect(predeploy).toContain('globalThis.console.error(error)')
    expect(predeploy).toContain("window.console.warn('โหลดข้อมูลช้า', error)")
    expect(predeploy).toContain('javascript:')
    expect(predeploy).toContain('vbscript:')
    expect(predeploy).toContain('postMessage\\\\s*\\\\(')
    expect(predeploy).toContain('ห้ามเรียก postMessage ตรงใน frontend source')
    expect(predeploy).toContain('addEventListener\\\\s*\\\\(')
    expect(predeploy).toContain('ห้ามใช้ลิงก์ protocol ที่รันโค้ดหรือ HTML ตรงใน frontend source')
    expect(predeploy).toContain('formats object-shaped env doctor errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped Supabase storage setup errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped e2e smoke errors without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped knowledge diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped required DB check diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped DB-test skip diagnostics without stringifying raw objects')
    expect(predeploy).toContain('formats object-shaped database health diagnostics without stringifying raw objects')
    expect(predeploy).toContain('redactUnknownDiagnosticText')
    expect(predeploy).toContain('object-shaped error')
    expect(predeploy).toContain('safeErrorTextForClassification')
    expect(predeploy).toContain('frontendErrorSecretPatterns')
    expect(predeploy).toContain('Lore/persona injection')
    expect(predeploy).toContain('New-tab links')
    expect(predeploy).toContain('reports raw auth error classifier regressions')
    expect(predeploy).toContain('error\\\\s*\\\\.\\\\s*message\\\\s*\\\\.\\\\s*toLowerCase')
    expect(predeploy).toContain('String\\\\s*\\\\(\\\\s*error\\\\s*\\\\)\\\\s*\\\\.\\\\s*toLowerCase')
    expect(predeploy).toContain('\\\\.test\\\\(\\\\s*error\\\\s*\\\\.\\\\s*message')
    expect(predeploy).toContain('error\\\\s*\\\\.\\\\s*message\\\\s*\\\\.\\\\s*match')
    expect(predeploy).toContain('setNote\\\\s*\\\\(\\\\s*error\\\\s+instanceof\\\\s+Error\\\\s*\\\\?\\\\s*error\\\\s*\\\\.\\\\s*message')
    expect(predeploy).toContain('state\\\\s*\\\\.\\\\s*error\\\\s*=\\\\s*action\\\\s*\\\\.\\\\s*error\\\\s*\\\\.\\\\s*message')
    expect(predeploy).toContain('rawUiErrorThrowPattern')
    expect(predeploy).toContain('rawUiErrorThrowPatternFor')
    expect(predeploy).toContain('rawFrontendErrorLogPatternFor')
    expect(predeploy).toContain('consoleErrorWarnAccessor')
    expect(predeploy).toContain('retrievedConsoleObjectValue')
    expect(predeploy).toContain('consoleObjectValue')
    expect(predeploy).toContain('consoleObjectMemberAccessor')
    expect(predeploy).toContain('consoleErrorWarnCallPrefix')
    expect(predeploy).toContain('reflectConsoleErrorWarnApplyPrefix')
    expect(predeploy).toContain(String.raw`globalThis\\s*(?:\\?\\.|\\.)\\s*`)
    expect(predeploy).toContain('${consoleObjectMemberAccessor}\\\\s*(?:(?:\\\\?\\\\.|\\\\.)\\\\s*(?:error|warn)|(?:\\\\?\\\\.)?\\\\s*\\\\[')
    expect(predeploy).toContain(String.raw`["\'](?:error|warn)["\']\\s*\\]`)
    expect(predeploy).toContain('rawFrontendErrorClassifierPatternFor')
    expect(predeploy).toContain('rawFrontendErrorRegexPatternFor')
    expect(predeploy).toContain('rawFrontendUserVisibleErrorPatternFor')
    expect(predeploy).toContain(String.raw`catch\\s*\\(\\s*([A-Za-z_$][\\w$]*)(?:\\s*:\\s*(?:unknown|any))?`)
    expect(predeploy).toContain('catch (problem)')
    expect(predeploy).toContain('catch (problem: unknown)')
    expect(predeploy).toContain('catch (problem: any)')
    expect(predeploy).toContain('reports typed catch-variable raw frontend errors')
    expect(predeploy).toContain("console.error(\\'")
    expect(predeploy).toContain("\\', problem)")
    expect(predeploy).toContain('console.warn(problem,')
    expect(predeploy).toContain('console.error(problem as Error)')
    expect(predeploy).toContain('console.warn((problem as Error),')
    expect(predeploy).toContain('console?.error(problem)')
    expect(predeploy).toContain('console.warn?.(problem,')
    expect(predeploy).toContain("console['error'](problem)")
    expect(predeploy).toContain("console?.['warn']?.(problem,")
    expect(predeploy).toContain('console.error.call(console, problem)')
    expect(predeploy).toContain("console.warn.apply(console, [problem, 'slow apply'])")
    expect(predeploy).toContain('console.error.bind(console)(problem)')
    expect(predeploy).toContain("console.warn.bind(console)('slow bind', problem)")
    expect(predeploy).toContain('Reflect.apply(console.error, console, [problem])')
    expect(predeploy).toContain("Reflect.apply(console.warn, console, ['slow reflect', problem])")
    expect(predeploy).toContain('window.console.error(problem)')
    expect(predeploy).toContain("globalThis.console.warn('slow global', problem)")
    expect(predeploy).toContain('problem.message.toLowerCase')
    expect(predeploy).toContain('String(problem).toLowerCase')
    expect(predeploy).toContain('(problem as Error).message.toLowerCase')
    expect(predeploy).toContain('String(problem as Error).toLowerCase')
    expect(predeploy).toContain('/admin_unauthorized|forbidden/i.test(problem.message)')
    expect(predeploy).toContain('/admin_unauthorized|forbidden/i.test((problem as Error).message)')
    expect(predeploy).toContain('setNotice(problem instanceof Error ? problem.message')
    expect(predeploy).toContain('setNotice(problem instanceof Error ? (problem as Error).message')
    expect(predeploy).toContain('rawFrontendErrorExpressionPatternFor')
    expect(predeploy).toContain('rawFrontendErrorMessageAccessPatternFor')
    expect(predeploy).toContain('auditRawUiErrorThrows')
    expect(predeploy).toContain('หน้า UI ห้าม throw raw error object จาก component/page')
    expect(predeploy).toContain('providerClassificationMessage')
    expect(predeploy).toContain('rawRouteErrorLogPattern')
    expect(predeploy).toContain('rawRouteErrorReturnPattern')
    expect(predeploy).toContain('content.matchAll(rawRouteErrorReturnPattern)')
    expect(predeploy).toContain("throw\\\\\\\\s*(?:\\\\\\\\(\\\\\\\\s*)?${rawErrorExpressionPatternFor('error')}")
    expect(predeploy).toContain("return\\\\\\\\s*(?:\\\\\\\\(\\\\\\\\s*)?${rawErrorExpressionPatternFor('error')}")
    expect(predeploy).toContain('rawRouteErrorReturnPatternFor')
    expect(predeploy).toContain('rawRouteErrorThrowPatternFor')
    expect(predeploy).toContain('rawRouteErrorLogPatternsFor')
    expect(predeploy).toContain('rawErrorArgumentPatternFor')
    expect(predeploy).toContain('rawErrorArrayElementPatternFor')
    expect(predeploy).toContain('rawErrorExpressionPatternFor')
    expect(predeploy).toContain("${consoleErrorWarnCallPrefix}[\\\\\\\\s\\\\\\\\S]*?,\\\\\\\\s*${rawErrorArgumentPatternFor('error')}")
    expect(predeploy).toContain('rawErrorMessageAccessPatternFor')
    expect(predeploy).toContain('rawErrorCodeAccessPatternFor')
    expect(predeploy).toContain('rawErrorDetailMessagePatternFor')
    expect(predeploy).toContain("rawErrorDetailMessagePatternFor('error')")
    expect(predeploy).toContain("rawErrorDetailDirectPatternFor('error')")
    expect(predeploy).toContain('rawAuthErrorResponseBypassPatternFor')
    expect(predeploy).toContain("rawAuthErrorResponseBypassPatternFor('error')")
    expect(predeploy).toContain(String.raw`const fieldGap = '\\\\s*,\\\\s*(?:[^{}]*?\\\\s*,\\\\s*)?'`)
    expect(predeploy).toContain(String.raw`catch\\s*\\(\\s*([A-Za-z_$][\\w$]*)(?:\\s*:\\s*(?:unknown|any))?`)
    expect(predeploy).toContain('catches alternate route catch variable names')
    expect(predeploy).toContain('catches type-asserted alternate route catch variables')
    expect(predeploy).toContain('catch (err: unknown)')
    expect(predeploy).toContain('console.error(err as Error)')
    expect(predeploy).toContain("console.warn('stream failed', (err as Error))")
    expect(predeploy).toContain('console.error.call(console, err)')
    expect(predeploy).toContain("console.warn.apply(console, ['stream failed', err])")
    expect(predeploy).toContain('console.error.call(console, err as Error)')
    expect(predeploy).toContain("console.warn.apply(console, ['stream failed', (err as Error)])")
    expect(predeploy).toContain('console.error.bind(console)(err)')
    expect(predeploy).toContain("console.warn.bind(console)('stream failed', err)")
    expect(predeploy).toContain('console.error.bind(console)(err as Error)')
    expect(predeploy).toContain("console.warn.bind(console)('stream failed', (err as Error))")
    expect(predeploy).toContain('Reflect.apply(console.error, console, [err])')
    expect(predeploy).toContain("Reflect.apply(console.warn, console, ['stream failed', err])")
    expect(predeploy).toContain('Reflect.apply(console.error, console, [err as Error])')
    expect(predeploy).toContain("Reflect.apply(console.warn, console, ['stream failed', (err as Error)])")
    expect(predeploy).toContain('globalThis.console.error(err)')
    expect(predeploy).toContain("globalThis.console.warn('stream failed', err)")
    expect(predeploy).toContain('globalThis.console.error(err as Error)')
    expect(predeploy).toContain("globalThis.console.warn('stream failed', (err as Error))")
    expect(predeploy).toContain("console.warn('stream failed', error as Error)")
    expect(predeploy).toContain("console?.['warn']?.('stream failed', error as Error)")
    expect(predeploy).toContain("console['error'](err)")
    expect(predeploy).toContain("console?.['warn']?.('stream failed', err)")
    expect(predeploy).toContain("console['error'](err as Error)")
    expect(predeploy).toContain("console?.['warn']?.('stream failed', (err as Error))")
    expect(predeploy).toContain('throw (err as Error)')
    expect(predeploy).toContain('return (cause as Error)')
    expect(predeploy).toContain('throw (error as Error)')
    expect(predeploy).toContain('return (error as Error)')
    expect(predeploy).toContain('(err as Error).message')
    expect(predeploy).toContain('String ( err as Error )')
    expect(predeploy).toContain('error: (err as AuthError).code, status: 401, message: (err as AuthError).message')
    expect(predeploy).toContain('detail: error instanceof Error ? (error as Error).message : String(error as Error)')
    expect(predeploy).toContain('detail: String(error as Error)')
    expect(predeploy).toContain('detail: (error as Error).message')
    expect(predeploy).toContain('rawAuthErrorResponseBypassPattern')
    expect(predeploy).toContain('ห้ามประกอบ AuthError response จาก error.code/error.message ตรงๆ')
    expect(predeploy).toContain('catches AuthError responses that bypass the public response helper')
    expect(predeploy).toContain('return { error: (error as AuthError).code, message: (error as AuthError).message }')
    expect(predeploy).toContain('return { error: (error as AuthError).code, status: 401, message: (error as AuthError).message }')
    expect(predeploy).toContain('return { message: (error as AuthError).message, status: 401, error: (error as AuthError).code }')
    expect(predeploy).toContain('return authErrorResponse(error)')
    expect(predeploy).toContain("${consoleErrorWarnCallPrefix}\\\\\\\\s*${rawErrorArgumentPatternFor('error')}")
    expect(predeploy).toContain("providerFailure[\\\\\\\\s\\\\\\\\S]*?,\\\\\\\\s*${rawErrorExpressionPatternFor('error')}")
    expect(predeploy).toContain('catches raw provider error logging after classification')
    expect(predeploy).toContain('console.error(error as Error)')
    expect(predeploy).toContain("console.warn((error as Error), 'seed slow')")
    expect(predeploy).toContain('console?.error(error)')
    expect(predeploy).toContain("console.warn?.(error, 'seed slow')")
    expect(predeploy).toContain("console['error'](error)")
    expect(predeploy).toContain("console?.['warn']?.(error, 'seed slow')")
    expect(predeploy).toContain('console.error.call(console, error)')
    expect(predeploy).toContain("console.warn.call(console, 'seed slow', error as Error)")
    expect(predeploy).toContain('console.error.apply(console, [error])')
    expect(predeploy).toContain("console.warn.apply(console, ['seed slow', error as Error])")
    expect(predeploy).toContain('console.error.bind(console)(error)')
    expect(predeploy).toContain("console.warn.bind(console)('seed slow', error as Error)")
    expect(predeploy).toContain('Reflect.apply(console.error, console, [error])')
    expect(predeploy).toContain("Reflect.apply(console.warn, console, ['seed slow', error as Error])")
    expect(predeploy).toContain('globalThis.console.error(error)')
    expect(predeploy).toContain("globalThis.console.warn('seed slow', error)")
    expect(predeploy).toContain("console['error']('สตรีมแชทไม่สำเร็จ:', providerFailure, error)")
    expect(predeploy).toContain("console.error.call(console, 'สตรีมแชทไม่สำเร็จ:', providerFailure, error)")
    expect(predeploy).toContain("console.warn.apply(console, ['สตรีมแชทไม่สำเร็จ:', providerFailure, error])")
    expect(predeploy).toContain("console.error.bind(console)('สตรีมแชทไม่สำเร็จ:', providerFailure, error)")
    expect(predeploy).toContain("Reflect.apply(console.error, console, ['สตรีมแชทไม่สำเร็จ:', providerFailure, error])")
    expect(predeploy).toContain("globalThis.console.error('สตรีมแชทไม่สำเร็จ:', providerFailure, error)")
    expect(predeploy).toContain('providerFailure, error as Error')
    expect(predeploy).toContain("console.warn?.('stream failed', error as Error)")
    expect(predeploy).toContain("console.warn.call(console, 'stream failed', error as Error)")
    expect(predeploy).toContain("console.error.apply(console, ['stream failed', error as Error])")
    expect(predeploy).toContain("console.warn.bind(console)('stream failed', error as Error)")
    expect(predeploy).toContain("Reflect.apply(console.warn, console, ['stream failed', error as Error])")
    expect(predeploy).toContain("globalThis.console.warn('stream failed', error as Error)")
    expect(predeploy).toContain('catches route raw error logging')
    expect(predeploy).toContain('catches route catch raw error returns')
    expect(predeploy).toContain('redacts secret-shaped provider details before classification output')
    expect(predeploy).toContain('creatorDraftRetryRawMessage')
    expect(predeploy).toContain('creatorDraftRetryMessage')
    expect(predeploy).toContain('classifies object-shaped provider failures without stringifying raw objects')
    expect(predeploy).toContain('retries object-shaped text model errors without stringifying raw objects')
    expect(predeploy).toContain('redacts text-model retry classifier input before matching transient hints')
    expect(predeploy).toContain('assertThaiFirstMarkdownHeadings')
    expect(predeploy).toContain('0020-discover-decision-markdown-heading-files.md')
    expect(predeploy).toContain('`qa:repo` ล่าสุดผ่านวันที่ 2026-05-31')
    expect(predeploy).toContain('memory audit ครอบ 36 Markdown files')
    expect(predeploy).toContain('Decision/predeploy handoff lock ล่าสุดอยู่ถึง')
    expect(predeploy).toContain('0026-lock-frontend-ui-route-error-guards.md')
    expect(predeploy).toContain('predeploy:check` audits decision Markdown dynamically')
    expect(predeploy).toContain('decision markdown files ถูก audit แบบ dynamic')
    expect(predeploy).toContain('stream live-provider handoff wording pass')
    expect(predeploy).toContain('missingDecisionIndexEntries')
    expect(predeploy).toContain('apps/backend/src/world-state.service.ts')
    expect(predeploy).toContain('frontend API helper contract')
    expect(predeploy).toContain('apps/frontend/src/lib/api.ts')
    expect(predeploy).toContain('ARG VITE_SUPABASE_ANON_PUBLIC=')
    expect(predeploy).toContain('VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_PUBLIC bun run build')
    expect(predeploy).toContain('สถานะโลกปัจจุบัน')
    expect(predeploy).toContain('Treat this as the current world state')
    expect(predeploy).toContain('uses a Thai-first prompt for live roleplay quality smoke')
    expect(predeploy).toContain('liveChatSmokePrompt')
    expect(predeploy).toContain('Reply as an atmospheric roleplay scene')
    expect(predeploy).toContain('apps/backend/prisma/qa-seed.ts')
    expect(predeploy).toContain('พูดกระชับแต่เป็นฉากครบ')
    expect(predeploy).toContain('ตอบสั้นแต่มีชั้นเชิง')
    expect(predeploy).toContain('^#\\s+\\d{4}\\s+-\\s+')
    expect(predeploy).toContain('ยังไม่มีข้อความที่ต้องมี')
    expect(predeploy).toContain("result.ok ? 'ผ่าน' : 'ไม่ผ่าน'")
    expect(predeploy).not.toContain("result.ok ? 'ok' : 'fail'")
    expect(predeploy).not.toContain('error: error instanceof Error ? error.message : String(error)')
    expect(predeploy).not.toContain('is missing ${missing.join')
    expect(predeploy).not.toContain('contains stale text')
  })

  test('locks Thai-first e2e labels for admin eval smoke', async () => {
    const predeploy = await readRepoFile('scripts/predeploy-check.ts')
    const e2eSmoke = await readRepoFile('tests/e2e/maprang-smoke.spec.ts')

    expect(e2eSmoke).toContain('ทดสอบคุณภาพพรอมป์และบริบท')
    expect(e2eSmoke).not.toContain('ทดสอบคุณภาพ prompt/context')
    expect(predeploy).toContain('ทดสอบคุณภาพพรอมป์และบริบท')
    expect(predeploy).toContain('prompt/context')
  })

  test('keeps the predeploy regression test in local and deployed QA gates', async () => {
    const packageJson = JSON.parse(await readRepoFile('package.json')) as { scripts?: Record<string, string> }
    const ciWorkflow = await readRepoFile('.github/workflows/ci.yml')
    const productionSmoke = await readRepoFile('.github/workflows/production-smoke.yml')
    const readme = await readRepoFile('README.md')
    const deploymentQa = await readRepoFile('DEPLOYMENT_QA.md')

    const qaRepo = packageJson.scripts?.['qa:repo'] ?? ''
    const qaLocal = packageJson.scripts?.['qa:local'] ?? ''
    const qaLocalOnlyCommands = qaLocal
      .split(/\s*&&\s*/)
      .map((command) => command.trim())
      .filter(Boolean)
    const qaLocalCommands = [qaRepo, qaLocal].flatMap((script) =>
      script
        .split(/\s*&&\s*/)
        .map((command) => command.trim())
        .filter(Boolean),
    )

    expect(packageJson.scripts?.['predeploy:check:test']).toBe('bun test scripts/predeploy-check.test.ts')
    expect(qaLocalOnlyCommands).toContain('bun run qa:repo')
    expect(qaLocalOnlyCommands).toContain('bun run smoke:doctor')
    expect(qaLocalOnlyCommands).toContain('bun run smoke:local')
    expect(qaLocalOnlyCommands).toContain('bun run api:smoke')
    expect(qaLocalCommands).toContain('bun run predeploy:check:test')
    expect(qaLocalCommands).toContain('bun run docs:commands')
    expect(qaLocalCommands).toContain('bun run docs:commands:test')
    expect(qaLocalCommands).toContain('bun run tests:audit')
    expect(qaLocalCommands).toContain('bun run tests:audit:test')
    expect(qaLocalCommands).toContain('bun run deploy:doctor:self-test')
    expect(qaLocalCommands).toContain('bun run security:audit')
    expect(qaLocalCommands).toContain('bun run security:audit:test')
    expect(qaLocalCommands).toContain('bun run import-cycle:audit')
    expect(qaLocalCommands).toContain('bun run import-cycle:audit:test')
    expect(qaLocalCommands).toContain('bun run api:audit')
    expect(qaLocalCommands).toContain('bun run api:audit:test')
    expect(qaLocalCommands).toContain('bun run frontend:env:test')
    expect(qaLocalCommands).toContain('bun run frontend:storage:test')
    expect(qaLocalCommands).toContain('bun run frontend:clipboard:test')
    expect(qaLocalCommands).toContain('bun run frontend:static:audit')
    expect(qaLocalCommands).toContain('bun run frontend:static:audit:test')
    expect(qaLocalCommands).toContain('bun run frontend:route:audit')
    expect(qaLocalCommands).toContain('bun run frontend:route:audit:test')
    expect(qaLocalCommands).toContain('bun run route-menu:audit')
    expect(qaLocalCommands).toContain('bun run route-menu:audit:test')
    expect(ciWorkflow.match(/name: ติดตั้ง dependencies ระดับ repo[\s\S]*?run: bun install --frozen-lockfile/g)?.length ?? 0).toBeGreaterThanOrEqual(2)
    expect(ciWorkflow).toContain('รัน local smoke จาก seed')
    expect(ciWorkflow).not.toContain('Install root dependencies')
    expect(ciWorkflow).toContain('bun run predeploy:check:test')
    expect(ciWorkflow).toContain('bun run docs:commands')
    expect(ciWorkflow).toContain('bun run docs:commands:test')
    expect(ciWorkflow).toContain('bun run tests:audit')
    expect(ciWorkflow).toContain('bun run tests:audit:test')
    expect(ciWorkflow).toContain('bun run deploy:doctor:self-test')
    expect(ciWorkflow).toContain('bun run frontend:env:test')
    expect(ciWorkflow).toContain('bun run frontend:storage:test')
    expect(ciWorkflow).toContain('bun run frontend:clipboard:test')
    expect(ciWorkflow).toContain('bun run frontend:static:audit')
    expect(ciWorkflow).toContain('bun run frontend:route:audit')
    expect(ciWorkflow).toContain('--build-arg VITE_SUPABASE_ANON_PUBLIC=ci-anon-public-key')
    expect(productionSmoke).toContain('bun run predeploy:check:test')
    expect(productionSmoke).toContain('bun run docs:commands')
    expect(productionSmoke).toContain('bun run docs:commands:test')
    expect(productionSmoke).toContain('bun run tests:audit')
    expect(productionSmoke).toContain('bun run tests:audit:test')
    expect(productionSmoke).toContain('bun run frontend:env:test')
    expect(productionSmoke).toContain('bun run frontend:storage:test')
    expect(productionSmoke).toContain('bun run frontend:clipboard:test')
    expect(productionSmoke).toContain('bun run frontend:static:audit')
    expect(productionSmoke).toContain('bun run frontend:route:audit')
    for (const docs of [readme, deploymentQa]) {
      expect(docs).toContain('bun run frontend:env:test')
      expect(docs).toContain('bun run frontend:storage:test')
      expect(docs).toContain('bun run frontend:clipboard:test')
    }
    for (const command of [
      'bun run security:audit',
      'bun run import-cycle:audit',
      'bun run api:audit',
      'bun run frontend:env:test',
      'bun run frontend:storage:test',
      'bun run frontend:clipboard:test',
      'bun run frontend:static:audit',
      'bun run frontend:route:audit',
      'bun run route-menu:audit',
    ]) {
      expect(ciWorkflow).toMatch(new RegExp(`-\\s+run:\\s+${command.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\r?\\n`))
      expect(productionSmoke).toMatch(new RegExp(`-\\s+run:\\s+${command.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\r?\\n`))
    }
    expect(productionSmoke).toContain('Backend URL ที่ต้องการทดสอบ')
    expect(productionSmoke).toContain('ตรวจ config ก่อนรัน smoke')
    expect(productionSmoke).toContain('รันทดสอบแชทจริงกับ AI คำสั่งนี้ใช้เครดิตผู้ให้บริการจริง')
    expect(productionSmoke).toContain('รันทดสอบสร้างรูปจริง คำสั่งนี้ใช้เครดิตสร้างรูปจริง')
    expect(productionSmoke).toContain('ยอดโทเคนขั้นต่ำของผู้ใช้ smoke ก่อนรันทดสอบแชทจริง')
    expect(productionSmoke).toContain('ตั้ง workflow input api_base_url หรือ repository secret SMOKE_API_BASE_URL ก่อนรัน smoke')
    expect(productionSmoke).not.toContain('Backend URL to test')
    expect(productionSmoke).not.toContain('รัน live AI chat smoke')
    expect(productionSmoke).not.toContain('รัน live image generation smoke')
    expect(productionSmoke).not.toContain('ยอดโทเคนขั้นต่ำของ smoke user ก่อนรัน live chat smoke')
    expect(productionSmoke).not.toContain('Validate smoke configuration')
    expect(productionSmoke).not.toContain('Minimum smoke-user token balance')
    expect(productionSmoke).not.toContain('Set workflow input api_base_url')
  })
})
